name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t chrisjohnson00/handbrake_plex_webhook:${GITHUB_REF##*/}
    - name: flake8
      run: docker run chrisjohnson00/handbrake_plex_webhook:${GITHUB_REF##*/} python -m flake8
    - name: Login to docker hub
      run: docker login --username=chrisjohnson00 --password=${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push the Docker image
      run: docker push chrisjohnson00/handbrake_plex_webhook:${GITHUB_REF##*/}
