name: BuildKite

on:
  push:
    branches: [ main ]
    tags:
      - v**
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buildkite/trigger-pipeline-action@v1.2.0
      env:
        PIPELINE: "my-org/my-deploy-pipeline"
        COMMIT: "HEAD"
        BRANCH: "master"
        MESSAGE: ":github: Triggered from a GitHub Action"
